### ISSUE TITLE
Is the 'I' channel of densepose data available?  

### ISSUE THREAD

**Issue by dancasas** [yumingj/DeepFashion-MultiModal#3]
Thanks for such a great work and interesting dataset!

I am trying to reproject color images into UV maps using the provided densepose annotations, however I think I need the <code>I</code> channel of the denseposes that maps the UV values into the corresponding island on the UV map. As defined in the original densepose paper [here](https://github.com/facebookresearch/detectron2/blob/main/projects/DensePose/doc/DENSEPOSE_IUV.md#Overview):

_For each detected object, the model predicts its coarse segmentation <code>S</code> (2 or 15 channels: foreground / background or background + 14 predefined body parts), fine segmentation <code>I</code> (25 channels: background + 24 predefined body parts) and local chart coordinates U and V._

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/2377307/200200491-9707de0d-08ce-48a0-a76e-b8ac476884db.png">

Is the <code>I</code> available? Or perhaps there is another way to use your provided densepose annotations to reproject the color images into the UV texture than I am missing?

Thanks!

**Comment by yumingj** [comment]
Hi @dancasas 

The densepose we provide is the IUV map. You can obtain the I channel like this: https://github.com/yumingj/Text2Human/blob/31eb3218b2208e18c126512f7098a6e82922ad83/data/pose_attr_dataset.py#L68

Thanks!
