### ISSUE TITLE
Typo in README-Labels-Shape Annotations-neckline

### ISSUE THREAD

**Issue by LOSKIw** [yumingj/DeepFashion-MultiModal#5]
In [Shape Annotations details](https://github.com/yumingj/DeepFashion-MultiModal#shape-annotations)
2 is followed by 4, while 3 still exist in the ann file
Not a serious problem but truly confused me at first
  
![screen shot](https://user-images.githubusercontent.com/48372803/212653358-2757b1a6-37d6-464f-8c6a-5291db7ace53.png)

**Comment by yumingj** [comment]
Hi, thanks for pointing this out. I have revised the readme. Sorry for the confusion.
