### ISSUE TITLE
Why do you say StyleGAN-Human used your dataset? I cannot find your dataset in their paper, or do you mean that their dataset is derived from yours? 

### ISSUE THREAD

**Issue by PeterPanTheGenius** [yumingj/DeepFashion-MultiModal#6]
Why do you say StyleGAN-Human used your dataset? I cannot find your dataset in their paper, or do you mean that their dataset is derived from yours? 
Just curious, have a good day.
Best Regards,

**Comment by yumingj** [comment]
Hi, thanks for your interest in our dataset.

The SHHQ dataset proposed in StyleGAN-Human includes the full-body images in our dataset. And they also use labels in our dataset to train the image editing models. Also, our human parsing maps are included in the SHHQ dataset.

Hope this address your concerns.

Thanks!
